In [49]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from proj1_helpers import *
from implementations import *
import codecs, json 
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Data_tr removing all samples with -999

In [ ]:
# import some data to test the functions
from helpers import *

ids_tr,predictions_tr,data_tr, ids_te,data_te = load_boson_data()

invalid_indexes= np.unique(np.where(data_tr == -999)[0])  
invalid_indexes   #"indexes" of the rows where -999 is present

In [ ]:
clean_data_tr = np.delete(data_tr,np.unique(np.where(data_tr == -999)[0]),0)

clean_data_tr.shape

# Data_tr replacing -999 with 0

with_zero_data_tr = np.where(data_tr == -999, 0, data_tr)

with_zero_data_tr.shape

# Data_tr replacing -999 with the mean/median/mfv

In [ ]:
# to do

# Correlation between features

In [ ]:
# some analysys with the help of pandas and seaborn
import pandas as pd
import seaborn as sbn
from proj1_helpers import *
from implementations import *

ndata = 100
data_path = "../dataset/train.csv"
_, data_loaded, _ = load_partial_csv_data(data_path, ndata)
print(data_loaded.shape)

In [ ]:
x_ = data_loaded
# x_, ndropped = drop_corr_columns(data_loaded, 0.5)
x_ = pd.DataFrame(x_)
x_.head(40)

In [ ]:
# visualize distribution of features and pairwise relationship using seaborn pairplot
sbn.pairplot(data)

In [ ]:
data.shape

In [ ]:
# compute and print the pairwise correlation between the columns in data frame

correlations = data.corr()
correlations

Features that have a strong correlation with other fatures:
* DER_tp_h
* DER_deltaeta_jet_jet
* DER_mass_jet_jet
* DER_prodeta_jet_jet
* DER_sum_pt
* DER_met_phi_centrality
* DER_lep_eta_centrality
* PRI_met_sumet
* PRI_jet_num
* PRI_jet_leading_pt
* PRI_jet_leading_eta
* PRI_jet_leading_phi
* PRI_jet_subleading_pt
* PRI_jet_subleading_eta
* PRI_jet_subleading_phi
* PRI_jet_all_pt

# Compute correlation matrix

In [39]:
# LOAD TRAIN DATA
data_path = "../dataset/train.csv"
y_loaded, data_loaded, _ = load_csv_data(data_path)

In [40]:
# LOAD TRAIN DATA
data_path = "../dataset/test.csv"
_, data_test_loaded, _ = load_csv_data(data_path)

In [41]:
data_loaded.shape, data_test_loaded.shape

((250000, 30), (568238, 30))

In [42]:
data_merged= np.concatenate((data_loaded,data_test_loaded), axis=0)
data_merged.shape

(818238, 30)

In [68]:
from implementations import *
data2 = standardize_final(data_merged)
data2.shape

(818238, 30)

In [72]:
np.nanmean(data2,axis=0)

array([ -3.17216387e-09,   1.03710716e-09,  -9.49157558e-10,
         2.75214382e-10,  -2.37154677e-09,  -4.24695293e-10,
         1.26353578e-10,   2.77264806e-09,  -2.20539680e-09,
        -6.19460966e-10,   5.35282624e-09,  -2.53746009e-10,
        -1.01104676e-09,   2.82057741e-10,  -2.95827309e-12,
         7.31771013e-12,   2.82354029e-10,  -4.66231381e-12,
        -3.33055435e-12,  -1.10220055e-09,  -2.13645860e-12,
         2.09908730e+02,   6.26473392e-10,   5.67837831e-10,
         8.28088141e-13,  -9.15971787e-12,   1.20276071e-09,
         1.60110842e-12,   1.99444829e-11,  -2.67166579e-09])

In [58]:
# CLEAN DATA: YOU MAY WANT TO CHAGE THIS STEP
#data = drop_columns_with_70_nan_ratio(data_merged)
data = fill_with_nan_list(data_merged, nan_values=[0, -999])
#data = sustitute_nans(data, substitutions=np.nanmean(data, axis=0))
data.shape

(818238, 30)

In [67]:

means = np.nanmean(data, axis=0)
std_devs = np.nanstd(data, axis=0)

data_std = data - means
data_std = data / whole_data_std_devs()

means = np.nanmean(data_std, axis=0)
std_devs = np.nanstd(data_std, axis=0)

means,std_devs

(array([  2.14019075e+00,   1.39218419e+00,   1.99938878e+00,
          9.12408517e-01,   1.38027241e+00,   9.34577485e-01,
         -2.31344554e-01,   3.04001515e+00,   8.65575236e-01,
          1.36615140e+00,   1.70247376e+00,  -1.06587704e-01,
          1.63461178e+00,   1.72536214e+00,  -9.61087031e-03,
         -7.24585534e-03,   2.10874050e+00,  -1.50926450e-02,
          2.72513983e-02,   1.28183183e+00,  -4.76360367e-03,
          2.09908730e+02,   2.24488816e+00,   1.39991806e+00,
         -7.01422387e-04,  -1.03879884e-02,   1.78122254e+00,
         -3.28284799e-03,  -5.76559837e-03,   1.21063717e+00]),
 array([   1.        ,    1.        ,    1.        ,    1.        ,
           1.        ,    1.        ,    1.        ,    1.        ,
           1.        ,    1.        ,    1.        ,    1.        ,
           1.        ,    1.        ,    1.        ,    1.        ,
           1.        ,    1.        ,    1.        ,    1.        ,
           1.        ,  126.81660841, 

In [51]:
raw_means = whole_data_means()
raw_std_devs = whole_data_std_devs()

means,raw_means

(array([  1.21867697e+02,   4.92532558e+01,   8.11405610e+01,
          5.78582923e+01,   2.40500975e+00,   3.72181050e+02,
         -8.29392140e-01,   2.37387138e+00,   1.89724461e+01,
          1.58596159e+02,   1.43877554e+00,  -1.27303822e-01,
          5.85210606e-01,   3.86981522e+01,  -1.16628927e-02,
         -1.31600006e-02,   4.66924138e+01,  -1.90822693e-02,
          4.94674822e-02,   4.16545265e+01,  -8.63571168e-03,
          2.09908730e+02,   1.63345672e+00,   8.49042850e+01,
         -1.24824003e-03,  -1.88594668e-02,   5.78102860e+01,
         -6.67041978e-03,  -1.04712859e-02,   1.22028164e+02]),
 [121.867697,
  49.2532558,
  81.140561,
  57.8582923,
  2.40500975,
  372.18105,
  -0.82939214,
  2.37387138,
  18.9724461,
  158.596159,
  1.43877554,
  -0.127303822,
  0.585210606,
  38.6981522,
  -0.0116628927,
  -0.0131600006,
  46.6924138,
  -0.0190822693,
  0.0494674822,
  41.6545265,
  -0.00863571168,
  209.90873,
  1.63345672,
  84.904285,
  -0.00124824003,
  -0.0188

In [ ]:
# COMPUTE AND STORE CORRELATION MATRIX
corr_matrix = np.abs(np.corrcoef(data.T)) 
file_path = "corr_matrix23.json"
json.dump(corr_matrix.tolist(), codecs.open(file_path, 'w', encoding='utf-8'), separators=(',', ':'), sort_keys=True, indent=4)

In [ ]:
# example: LOAD CORRELATION MATRIX
file_path = "corr_matrix23.json"
obj_text = codecs.open(file_path, 'r', encoding='utf-8').read()
b_new = json.loads(obj_text)
corr_matrix_loaded = np.array(b_new)

In [ ]:
# exaple: GET CORRELATED COLUMNS
corr_matrix = np.abs(corr_matrix) > 0.6
# remove i from the list (i is surely correlated to himself)
for i in range(23):
    corr_matrix[i][i] = False
    
correlated_to = {}
for i in range(23):
    c = np.where(corr_matrix[i])[0]
    if len(c) > 0: # if it is not correlated to any other column then ignore it
        correlated_to[i] = c
correlated_to

## Plot ditributions 

In [ ]:
# plot data as it is
plot_distributions(data_loaded, y_loaded, col_labels = column_labels(), title = "distribution_rawData")

In [ ]:
# plot data after cleaning it is
x_cleaned, keptCols = clean_x(data_loaded, 0.7, subs_func = np.nanmean)

plot_distributions(x_cleaned, y_loaded, col_labels = keptCols, title = "distribution_cleanedData_999=mean_0=mean")

In [ ]:
# plot data after cleaning it is
x_cleaned, keptCols = clean_x(data_loaded, 0.7, subs_func = None)

plot_distributions(x_cleaned, y_loaded, col_labels = keptCols, title = "distribution_cleanedData_999=999_0=0")

In [ ]:
# better norm the hist to have a clearer idea of the proportions
f, ax = plt.subplots(2, 2)
dataset1 = [0, 0, 0, 0, 1, 2, 4, 6]
dataset2 = [0, 0, 1, 6]

ax[0][0].hist(dataset1, histtype='step',color="red", normed=True)
ax[0][1].hist(dataset1, histtype='step',color="red", normed=False)


ax[1][0].hist(dataset2, histtype='step', color="blue", normed=True)
ax[1][1].hist(dataset2, histtype='step', color="blue", normed=False)


## -999 values analysis

In [ ]:
# there are three groups of columns with the -999 values in the same positions
print(np.sum(x_loaded == -999, axis=0).tolist())

In [ ]:
import pandas as pd
data = pd.DataFrame(data_loaded)

pri = np.where(column_labels() == "PRI_jet_num")
dropped = list(set(range(30))- set([0,  1,  2,  3,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 29]))
d = data[np.any(data==-999, axis=1)].loc[:, np.append(dropped ,pri)]

d[d[22] <= 1].head()

In [ ]:
d[d[22] > 1].head()

In [ ]:
plot_features(data_loaded)

### Percentile

In [6]:
data_merged = fill_with_nan_list(data_merged, nan_values=[0, -999])
data_merged.shape

(818238, 30)

In [65]:
list(range(0, 101, 5))

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [66]:
# [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]
scan_perc = list(range(0, 101, 5))
col_perc = np.zeros((len(scan_perc), data_merged.shape[1]))
for col in range(data_merged.shape[1]):
    for i, p in enumerate(scan_perc):
         col_perc[i, col] = np.nanpercentile(data_merged[:, col], p)
col_perc.shape

(21, 30)

In [67]:
# store both the computed percentiles and the list of % to which they correspond
file_path = "percentiles.json"
map_ = {
    "scan_perc": scan_perc,
    "col_perc": col_perc.tolist()
}
json.dump(map_, codecs.open(file_path, 'w', encoding='utf-8'), separators=(',', ':'), sort_keys=True, indent=4)

## Other approach: split data depending on jet number

### Why divide data depending on jet numbers and which columns can we drop?

Observations: most of the -999 value are associated with jet number <= 1. The only feature that still contains some -999 values is the first one.

In [96]:
all_data = data_merged.copy()

In [12]:
all_data.shape

(818238, 30)

Divide the data depending on the jet number (column 22) that is a categorical number in {0, 1, 2, 3}

In [97]:
jets_0 = all_data[all_data[:, 22]==0, :]
jets_1 = all_data[all_data[:, 22]==1, :]
jets_2 = all_data[all_data[:, 22]==2, :]
jets_3 = all_data[all_data[:, 22]==3, :]
jets_0.shape, jets_1.shape, jets_2.shape, jets_3.shape 

((327371, 30), (252882, 30), (165027, 30), (72958, 30))

Where are the -999 values?
- jet = 0: columns [4, 5, 6, 12, 23, 24, 25, 26, 27, 28] contain only -999 values, 26.1% of entries in the first column have -999
- jet = 1: columns [4, 5, 6, 12, 26, 27, 28] contain only -999 values, 7.6% of entries in the first column have -999
- jet = 2: 3% of entries in the first column have -999
- jet = 3: 1.4% of entries in the first column have -999

The two tables relative to jet 2 and jet 3 could be merged. The -999 values in the first column will be removed from that column and a boolean column will be created to indicate the position of the -999 values.

In [ ]:
for jet, cur_set in enumerate([jets_0, jets_1, jets_2, jets_3]):
    print("Features in the dataset with jet=", jet, "contains this many values != -999")
    for col in range(30):
        print(col, np.sum(cur_set[:, col] != -999))
    print()

Where are the 0 values?
- jet = 0: column 29 contains only 0s. (and, obviously, column 22 since it stores the jet num)
- jet = 1: spread
- jet = 2: spread
- jet = 3: spread

In [ ]:
for jet, cur_set in enumerate([jets_0, jets_1, jets_2, jets_3]):
    print("Features in the dataset with jet=", jet, "contains this many values != 0")
    for col in range(30):
        print(col, np.sum(cur_set[:, col] != 0))
    print()

After this first step we surely want to drop the following columns since they do not contain any useful information:
- jet = 0: [4, 5, 6, 12, 22, 23, 24, 25, 26, 27, 28, 29]
- jet = 1: [4, 5, 6, 12, 22, 26, 27, 28] 
- jet = 2: [22]
- jet = 3: [22]

### Divide data and compute the correlation matrix 

We now divide our data, drop the above columns and verify if there are some highly correlated features. If so, it is worth trying to drop all but 1 column in a set of correlated features.

In [109]:
datasets = split_input_data(data_merged) # split and drop
datasets[0].shape, datasets[1].shape, datasets[2].shape, datasets[3].shape

((327371, 18), (252882, 22), (165027, 29), (72958, 29))

In [116]:
corr_matrices = [None]*4
for jet in range(4):
    # don't consider the first column since it contains nan values (we will simply keep that column)
    corr_matrices[jet] = np.corrcoef(datasets[jet][:, 1:].T) 
corr_matrices[0].shape, cor_matrices[1].shape, cor_matrices[2].shape, cor_matrices[3].shape

((17, 17), (21, 21), (28, 28), (28, 28))

In [114]:
[{}]*4

[{}, {}, {}, {}]

In [121]:
# compute the mapping of correlations > min_corr
min_corr = 0.7
corr_mappings = [{}]*4
for jet in range(4):
    corr_matrix_bool = np.abs(corr_matrices[jet]) > min_corr 
    nfeature = corr_matrix_bool.shape[0]
    # i is surely correlated to itself, drop that (useless) information
    for i in range(nfeature):
        corr_matrix_bool[i][i] = False

    # compute the mapping of correlations
    for i in range(nfeature):
        c = np.where(corr_matrix_bool[i])[0].tolist()
        if len(c) > 0: # if it is not correlated to any other column then ignore it
            corr_mappings[jet][i] = c

In [122]:
corr_mappings[0]

{0: [14],
 2: [18],
 3: [4, 5],
 4: [3],
 5: [3],
 6: [11],
 8: [20, 21, 24, 27],
 9: [15],
 11: [6],
 14: [0],
 15: [9],
 16: [2, 5, 17, 20],
 17: [2, 5, 16, 20],
 18: [2],
 20: [8, 21, 24, 27],
 21: [8, 20, 27],
 24: [8, 20, 27],
 27: [8, 20, 21, 24]}

### Compute mean and std

We must use the same standardisation process both for the training and for predicting. Since the -999 values will be dropped from the first column I remove them to compute the mean and the std.

In [102]:
data_merged.shape

(818238, 30)

In [103]:
datasets = split_input_data(data_merged)
datasets[0].shape, datasets[1].shape, datasets[2].shape, datasets[3].shape

((327371, 18), (252882, 22), (165027, 29), (72958, 29))

In [106]:
corr_jet0 = np.corrcoef(datasets[0][:, 1:].T)
corr_jet0.shape

(17, 17)

In [66]:
d = datasets[0]
for col in range(d.shape[1]):
    print(np.all(d[:, col]==d[:, col][0]))

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
